### PR TITLE
Adding a dir and script for analysis of CRU data for a user guide

### PR DESCRIPTION
**Pull request by feggleton**
I would like to add a 'cru' directory and a notebook within that for users to access for help in analysing cru data

### CODE REVIEW

**Comment by feggleton** [comment]
@agstephens Could you review my CRU dataset notebook to go into the ceda notebooks repo so I can point users to this for help with analysis

**Comment by agstephens** [comment]
@feggleton sorry for the delay in getting to this. 

Overall, the Notebook looks great - with lots of explanation of what is happening. My only suggestions for change are:

1. Some of the bulleted lists have `</li>` tags on the end - which can be removed.
2. In various sections, you have a bulleted list where you explain what is happening line-by-line in the code. As the format of the bullets is all normal text - it is quite hard to read the python code snippets. I would recommend that you could remove the bullets, and use comments and white-space within the code snippets themselves. This would mean that the reader is able to see the code nicely formatted (and colourised) and the comments before each line/block of code will explain what is happening. This approach would require no additional wording, just moving the wording from the bullets in to comments within the python code.

Good job :-)

**Comment by feggleton** [comment]
Thanks @agstephens Have made those changes now :)

**Comment by agstephens** [comment]
Thanks @feggleton . I've merged. 👍

**Pull request merged**
