### PR TITLE
venv replacement

### LINKED ISSUE #28: Ideas for virtualenv replacement
It appears with modern Python we lose the "activate_this.py" script which used to allow activation from within a Python session. Instead, you can either do:

```
import pip
pip.main(["install",  "cerberus"])
import cerberus
```

...which will install into a `.local/...` directory.

In the instance when you need multiple environments, this might work:

https://stackoverflow.com/questions/2915471/install-a-python-package-into-a-different-directory-using-pip

I.e. override the target directory - and put different envs in different places - then remember to do `sys.path.insert(...)` to tell your session where to find a package.

### PR DESCRIPTION
**Pull request by Mahir-Sparkess**
**Reformatting:**

- moved `ceda-notebooks/notebooks/mngmnt/` to `ceda-notebooks/scripts`
- moved `gridlines.py` to `scripts`

**venv replacement**

- changed the `venv_utils.py` so that it works without `venv` and `activate_this.py`
- changed the methods and required parameters.

**notebooks**

- changed how venvs are created in the notebooks to utilise the script instead.
- proofed the notebooks using the jasmin notebook service.

### CODE REVIEW

**Review by agstephens — CHANGES_REQUESTED** [review]
@Mahir-Sparkess this looks good. One suggestion:

- your code looks for `lib/python3.8/site-packages`
- future versions of jaspy will use later versions of python
- maybe you could construct the string from:
```
import sys
sp_dir = "lib/python{}.{}/site-packages".format(sys.version_info.major, sys.version_info.minor)
```

or

```
import site
sp_dir = site.getsitepackages()
```

**Comment by Mahir-Sparkess** [comment]
Thanks Ag, changed the string to format the python version now. 👍

**Comment by agstephens** [comment]
Hi @Mahir-Sparkess, another quick (I hope) change request. When setting up the imports of the venv_utils library, I prefer:

```
import os
import sys
sys.path.append('../../../')

from scripts.utils import venv_utils
```

instead of:

```
os.chdir('../../..')
```

I think it is less confusing if we avoid changing the working directory - which could impact where outputs are written further down the notebooks.

**Comment by Mahir-Sparkess** [comment]
> Hi @Mahir-Sparkess, another quick (I hope) change request. When setting up the imports of the venv_utils library, I prefer:
> 
> ```
> import os
> import sys
> sys.path.append('../../../')
> 
> from scripts.utils import venv_utils
> ```
> 
> instead of:
> 
> ```
> os.chdir('../../..')
> ```
> 
> I think it is less confusing if we avoid changing the working directory - which could impact where outputs are written further down the notebooks.

Yep, just an easy find and replace. Thanks @agstephens, makes sense for file creation which I wouldn't catch in the pytest.

**Comment by amanning9** [comment]
@Mahir-Sparkess @agstephens quick poke to maybe take another look at this when you get a chance, please: the way this tutorial creates a virtual environment is currently broken, which stops the notebook from working!

**Comment by agstephens** [comment]
@Mahir-Sparkess How confident are you that the latest fix solves the problem of the venv creation? It's tricky to review because the notebook format obscures the changes.

**Comment by Mahir-Sparkess** [comment]
> @Mahir-Sparkess How confident are you that the latest fix solves the problem of the venv creation? It's tricky to review because the notebook format obscures the changes.

@agstephens The venv creation has been solved for a while and works on the notebooks service + ssh vscode. 👍 

I do have a discrepancy where some notebooks fail the pytest run as it can't find certain packages that should be in jaspy, unrelated to the venv. However, they all run fine on the notebooks service.

**Comment by agstephens** [comment]
@amanning9: Please test this out on `master` and let us know if the broken notebook is working again for you.

@Mahir-Sparkess: is it worth us trying to capture the dependencies from each notebook and put them all in a conda `environment.yml` file so that we know they will all run. The tests would be slower but would be comprehensive.

**Comment by amanning9** [comment]
@agstephens @Mahir-Sparkess 

The notebook I had a user query about (https://github.com/cedadev/ceda-notebooks/blob/master/notebooks/training/intro/notebook-tour-part-6.ipynb) seems to create venvs successfully and install things to them OK, so on that front you can count it as fixed, thanks!

However, I'll just highlight that I do get the following telling-off from pip:
image
Perhaps not currently important, but worth noting!

**Pull request merged**
